USE ROLE MRK_ROLE;
USE WAREHOUSE ANALYTICS_WH;
USE DATABASE RAW_DATA;
USE SCHEMA MARKETING;

-- SELECT THE 10 CUSTOMER WHO SPENT THE MOST
CREATE OR REPLACE VIEW TOP_CUSTOMERS ("CUSTOMER_ID", NAME, SURNAME, EMAIL, "TOTAL_PRICE")
AS
  SELECT TRANSACTIONS_EXPLODED.CUSTOMER_ID,
    NAME,
    SURNAME,
    EMAIL,
    SUM(PRICE)
  FROM TRANSACTIONS_EXPLODED
  JOIN "RAW_DATA"."SALES"."CUSTOMERS" ON "RAW_DATA"."SALES"."CUSTOMERS".CUSTOMER_ID = TRANSACTIONS_EXPLODED.CUSTOMER_ID
  GROUP BY TRANSACTIONS_EXPLODED.CUSTOMER_ID, NAME, SURNAME, EMAIL
  ORDER BY SUM(PRICE) DESC
  LIMIT 10;

-- SELECT THE 10 BEST SELLING PRODUCTS
SELECT TRANSACTIONS_EXPLODED.PRODUCT_ID,
DESCRIPTION,
CATEGORY,
COUNT(*)
FROM TRANSACTIONS_EXPLODED
JOIN "RAW_DATA"."SALES"."PRODUCTS" ON "RAW_DATA"."SALES"."PRODUCTS".PRODUCT_ID = TRANSACTIONS_EXPLODED.PRODUCT_ID
GROUP BY TRANSACTIONS_EXPLODED.PRODUCT_ID, DESCRIPTION, CATEGORY
ORDER BY COUNT(*) DESC
LIMIT 5;

--WHICH PRODUCT REPORTS THE GREATES INCOME
SELECT TRANSACTIONS_EXPLODED.PRODUCT_ID,
DESCRIPTION,
COUNT(*) AS "TOTAL SOLD",
SUM(PRICE) AS "TOTAL INCOME"
FROM TRANSACTIONS_EXPLODED
JOIN "RAW_DATA"."SALES"."PRODUCTS" ON "RAW_DATA"."SALES"."PRODUCTS".PRODUCT_ID = TRANSACTIONS_EXPLODED.PRODUCT_ID
GROUP BY TRANSACTIONS_EXPLODED.PRODUCT_ID, DESCRIPTION
ORDER BY SUM(PRICE) DESC
LIMIT 5;


--WHAT IS THE ITEM THE 1# CUSTOMER BOUGHT AND HOW MUCH WAS SPENT ON IT
SELECT TOP 1 COUNT(*) AS "ITEMS PURCHASED",SUM(PRICE) AS "TOTAL SPENT", TRANSACTIONS_EXPLODED.PRODUCT_ID, DESCRIPTION, EMAIL
FROM TRANSACTIONS_EXPLODED
JOIN "RAW_DATA"."SALES"."PRODUCTS" ON "RAW_DATA"."SALES"."PRODUCTS".PRODUCT_ID = TRANSACTIONS_EXPLODED.PRODUCT_ID
JOIN "RAW_DATA"."SALES"."CUSTOMERS" ON "RAW_DATA"."SALES"."CUSTOMERS".CUSTOMER_ID = TRANSACTIONS_EXPLODED.CUSTOMER_ID
WHERE TRANSACTIONS_EXPLODED.CUSTOMER_ID = (SELECT TOP 1 CUSTOMER_ID FROM TOP_CUSTOMERS)
GROUP BY TRANSACTIONS_EXPLODED.PRODUCT_ID, DESCRIPTION, EMAIL
ORDER BY COUNT(*) DESC;
