USE ROLE ACCOUNTADMIN;
USE DATABASE RAW_DATA;
USE SCHEMA SALES;

--CREATE STORAGE INTEGRATION
-- https://docs.snowflake.com/en/user-guide/data-load-s3-config-storage-integration.html
CREATE STORAGE INTEGRATION AWS_S3_EXERCISE
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::547183102522:role/mysnowflakerole'
ENABLED = TRUE
STORAGE_ALLOWED_LOCATIONS = ('s3://exercise-snowflake/');

--MODIFY IAM ROLE USING THE IAM_USER_ARN AND EXTERNAL_ID
DESC INTEGRATION AWS_S3_EXERCISE;

--MODIFY PERMISIONS SYSADMIN
GRANT USAGE ON INTEGRATION AWS_S3_EXERCISE TO ROLE SYSADMIN;

--CREATE EXTERNAL STAGE
USE ROLE SYSADMIN;
USE DATABASE RAW_DATA;
USE SCHEMA SALES;

CREATE OR REPLACE STAGE S3_RAW_DATA
STORAGE_INTEGRATION = AWS_S3_EXERCISE
URL = 's3://exercise-snowflake/';

list @S3_RAW_DATA;